version: "3.8"

services:
  db:
    image: postgres:14.3-alpine@sha256:5973fec8d8284c8961ac3c23945e52d533dd0d21cc7b3c7dd7a46fd199bed4a4
    container_name: membershipmgmtdb
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
        - "5430:5432"

  membershipmgmtdbapp:
    image: membershipmgmtapp-hornyaklevi
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8080:8080"
    build:
      context: "./"
      dockerfile: "Dockerfile"