/*
 * Copyright (c) 2022. Levente Hornyák
 */

DROP TABLE IF EXISTS country CASCADE;

CREATE TABLE IF NOT EXISTS country
(
    code    varchar(2)   NOT NULL PRIMARY KEY CHECK (upper(code) = code),
    name_hu varchar(255) NOT NULL,
    name_en varchar(255) NOT NULL
);

INSERT INTO country (code, name_hu, name_en)
VALUES ('AD', 'Andorra', 'Andorra'),
       ('AE', 'Egyesült Arab Emírségek', 'United Arab Emirates'),
       ('AF', 'Afganisztán', 'Afghanistan'),
       ('AG', 'Antigua és Barbuda', 'Antigua and Barbuda'),
       ('AI', 'Anguilla', 'Anguilla'),
       ('AL', 'Albánia', 'Albania'),
       ('AM', 'Örményország', 'Armenia'),
       ('AN', 'Holland Antillák', 'Netherlands Antilles'),
       ('AO', 'Angola', 'Angola'),
       ('AQ', 'Antarktisz', 'Antarctica'),
       ('AR', 'Argentína', 'Argentina'),
       ('AS', 'Amerikai Szamoa', 'American Samoa'),
       ('AT', 'Ausztria', 'Austria'),
       ('AU', 'Ausztrália', 'Australia'),
       ('AW', 'Aruba', 'Aruba'),
       ('AX', 'Åland-szigetek', 'Aland Islands'),
       ('AZ', 'Azerbajdzsán', 'Azerbaijan'),
       ('BA', 'Bosznia-Hercegovina', 'Bosnia and Herzegovina'),
       ('BB', 'Barbados', 'Barbados'),
       ('BD', 'Banglades', 'Bangladesh'),
       ('BE', 'Belgium', 'Belgium'),
       ('BF', 'Burkina Faso', 'Burkina Faso'),
       ('BG', 'Bulgária', 'Bulgaria'),
       ('BH', 'Bahrein', 'Bahrain'),
       ('BI', 'Burundi', 'Burundi'),
       ('BJ', 'Benin', 'Benin'),
       ('BL', 'Saint-Barthélemy', 'Saint Barthélemy'),
       ('BM', 'Bermuda', 'Bermuda'),
       ('BN', 'Brunei', 'Brunei Darussalam'),
       ('BO', 'Bolívia', 'Bolivia'),
       ('BR', 'Brazília', 'Brazil'),
       ('BS', 'Bahama-szigetek', 'Bahamas'),
       ('BT', 'Bhután', 'Bhutan'),
       ('BV', 'Bouvet-sziget', 'Bouvet Island'),
       ('BW', 'Botswana', 'Botswana'),
       ('BY', 'Belarusz/Fehéroroszország', 'Belarus'),
       ('BZ', 'Belize', 'Belize'),
       ('CA', 'Kanada', 'Canada'),
       ('CC', 'Kókusz-szigetek', 'Cocos (Keeling) Islands'),
       ('CD', 'Kongói Demokratikus Köztársaság', 'Congo, The Democratic Republic of '),
       ('CF', 'Közép-afrikai Köztársaság', 'Central African Republic'),
       ('CG', 'Kongó', 'Congo'),
       ('CH', 'Svájc', 'Switzerland'),
       ('CI', 'Elefántcsontpart', 'Cote d''Ivoire'),
       ('CK', 'Cook-szigetek', 'Cook Islands'),
       ('CL', 'Chile', 'Chile'),
       ('CM', 'Kamerun', 'Cameroon'),
       ('CN', 'Kína', 'China'),
       ('CO', 'Kolumbia', 'Colombia'),
       ('CR', 'Costa Rica', 'Costa Rica'),
       ('CU', 'Kuba', 'Cuba'),
       ('CV', 'Zöld-foki-szigetek', 'Cabo Verde'),
       ('CW', 'Curaçao', 'Curaçao'),
       ('CX', 'Karácsony-sziget', 'Christmas Island'),
       ('CY', 'Ciprus', 'Cyprus'),
       ('CZ', 'Csehország', 'Czechia'),
       ('CS', 'Szerbia és Montenegro', 'Serbia and Montenegro'),
       ('DE', 'Németország', 'Germany'),
       ('DJ', 'Dzsibuti', 'Djibouti'),
       ('DK', 'Dánia', 'Denmark'),
       ('DM', 'Dominika', 'Dominica'),
       ('DO', 'Dominikai Köztársaság', 'Dominican Republic'),
       ('DZ', 'Algéria', 'Algeria'),
       ('EC', 'Ecuador', 'Ecuador'),
       ('EE', 'Észtország', 'Estonia'),
       ('EG', 'Egyiptom', 'Egypt'),
       ('EH', 'Nyugat-Szahara', 'Western Sahara'),
       ('ER', 'Eritrea', 'Eritrea'),
       ('ES', 'Spanyolország', 'Spain'),
       ('ET', 'Etiópia', 'Ethiopia'),
       ('FI', 'Finnország', 'Finland'),
       ('FJ', 'Fidzsi', 'Fiji'),
       ('FK', 'Falkland-szigetek', 'Falkland Islands (Malvinas)'),
       ('FM', 'Mikronézia', 'Micronesia, Federated States of'),
       ('FO', 'Feröer szigetek', 'Faroe Islands'),
       ('FR', 'Franciaország', 'France'),
       ('GA', 'Gabon', 'Gabon'),
       ('GB', 'Egyesült Királyság', 'United Kingdom'),
       ('GD', 'Grenada', 'Grenada'),
       ('GE', 'Grúzia', 'Georgia'),
       ('GF', 'Francia Guyana', 'French Guiana'),
       ('GG', 'Guernsey', 'Guernsey'),
       ('GH', 'Ghána', 'Ghana'),
       ('GI', 'Gibraltár', 'Gibraltar'),
       ('GL', 'Grönland', 'Greenland'),
       ('GM', 'Gambia', 'Gambia'),
       ('GN', 'Guinea', 'Guinea'),
       ('GP', 'Guadeloupe', 'Guadeloupe'),
       ('GQ', 'Egyenlítői-Guinea', 'Equatorial Guinea'),
       ('GR', 'Görögország', 'Greece'),
       ('GS', 'Déli-Georgia és Déli-Sandwich-szigetek', 'South Georgia & The South Sandwich Islands'),
       ('GT', 'Guatemala', 'Guatemala'),
       ('GU', 'Guam', 'Guam'),
       ('GW', 'Bissau-Guinea', 'Guinea-Bissau'),
       ('GY', 'Guyana', 'Guyana'),
       ('HK', 'Hongkong', 'Hong Kong'),
       ('HM', 'Heard-sziget és McDonald-szigetek', 'Heard Island and McDonald Islands'),
       ('HN', 'Honduras', 'Honduras'),
       ('HR', 'Horvátország', 'Croatia'),
       ('HT', 'Haiti', 'Haiti'),
       ('HU', 'Magyarország', 'Hungary'),
       ('ID', 'Indonézia', 'Indonesia'),
       ('IE', 'Írország', 'Ireland'),
       ('IL', 'Izrael', 'Israel'),
       ('IM', 'Man-sziget', 'Isle of Man'),
       ('IN', 'India', 'India'),
       ('IO', 'Brit Indiai-óceáni Terület', 'British Indian Ocean Territory'),
       ('IQ', 'Irak', 'Iraq'),
       ('IR', 'Irán', 'Iran, Islamic Republic of'),
       ('IS', 'Izland', 'Iceland'),
       ('IT', 'Olaszország', 'Italy'),
       ('JE', 'Jersey', 'Jersey'),
       ('JM', 'Jamaica', 'Jamaica'),
       ('JO', 'Jordánia', 'Jordan'),
       ('JP', 'Japán', 'Japan'),
       ('KE', 'Kenya', 'Kenya'),
       ('KG', 'Kirgizisztán', 'Kyrgyzstan'),
       ('KH', 'Kambodzsa', 'Cambodia'),
       ('KI', 'Kiribati', 'Kiribati'),
       ('KM', 'Comore-szigetek', 'Comoros'),
       ('KN', 'Saint Kitts és Nevis', 'Saint Kitts & Nevis'),
       ('KP', 'Észak-Korea', 'Korea, Democratic People''s Republic of'),
       ('KR', 'Dél-Korea', 'Korea, Republic of'),
       ('KW', 'Kuvait', 'Kuwait'),
       ('KY', 'Kajmán-szigetek', 'Cayman Islands'),
       ('KZ', 'Kazahsztán', 'Kazakstan'),
       ('LA', 'Laosz', 'Lao, People''s Democratic Republic'),
       ('LB', 'Libanon', 'Lebanon'),
       ('LC', 'Saint Lucia', 'Saint Lucia'),
       ('LI', 'Liechtenstein', 'Liechtenstein'),
       ('LK', 'Srí Lanka', 'Sri Lanka'),
       ('LR', 'Libéria', 'Liberia'),
       ('LS', 'Lesotho', 'Lesotho'),
       ('LT', 'Litvánia', 'Lithuania'),
       ('LU', 'Luxemburg', 'Luxembourg'),
       ('LV', 'Lettország', 'Latvia'),
       ('LY', 'Líbia', 'Libya'),
       ('MA', 'Marokkó', 'Morocco'),
       ('MC', 'Monaco', 'Monaco'),
       ('MD', 'Moldova', 'Moldova, Republic of'),
       ('ME', 'Montenegró', 'Montenegro'),
       ('MF', 'Saint-Martin', 'Saint Martin'),
       ('MG', 'Madagaszkár', 'Madagascar'),
       ('MH', 'Marshall-szigetek', 'Marshall Islands'),
       ('MK', 'Észak-Macedónia', 'North Macedonia'),
       ('ML', 'Mali', 'Mali'),
       ('MM', 'Mianmar/Burma', 'Myanmar'),
       ('MN', 'Mongólia', 'Mongolia'),
       ('MO', 'Makaó', 'Macao'),
       ('MP', 'Északi-Mariana-szigetek', 'Northern Mariana Islands'),
       ('MQ', 'Martinique', 'Martinique'),
       ('MR', 'Mauritánia', 'Mauritania'),
       ('MS', 'Montserrat', 'Montserrat'),
       ('MT', 'Málta', 'Malta'),
       ('MU', 'Mauritius', 'Mauritius'),
       ('MV', 'Maldív-szigetek', 'Maldives'),
       ('MW', 'Malawi', 'Malawi'),
       ('MX', 'Mexikó', 'Mexico'),
       ('MY', 'Malajzia', 'Malaysia'),
       ('MZ', 'Mozambik', 'Mozambique'),
       ('NA', 'Namíbia', 'Namibia'),
       ('NC', 'Új-Kaledónia', 'New Caledonia'),
       ('NE', 'Niger', 'Niger'),
       ('NF', 'Norfolk-sziget', 'Norfolk Island'),
       ('NG', 'Nigéria', 'Nigeria'),
       ('NI', 'Nicaragua', 'Nicaragua'),
       ('NL', 'Hollandia', 'Netherlands'),
       ('NO', 'Norvégia', 'Norway'),
       ('NP', 'Nepál', 'Nepal'),
       ('NR', 'Nauru', 'Nauru'),
       ('NU', 'Niue', 'Niue'),
       ('NZ', 'Új-Zéland', 'New Zealand'),
       ('OM', 'Omán', 'Oman'),
       ('PA', 'Panama', 'Panama'),
       ('PE', 'Peru', 'Peru'),
       ('PF', 'Francia Polinézia', 'French Polynesia'),
       ('PG', 'Pápua Új-Guinea', 'Papua New Guinea'),
       ('PH', 'Fülöp-szigetek', 'Philippines'),
       ('PK', 'Pakisztán', 'Pakistan'),
       ('PL', 'Lengyelország', 'Poland'),
       ('PM', 'Saint-Pierre és Miquelon', 'Saint Pierre and Miquelon'),
       ('PN', 'Pitcairn-szigetek', 'Pitcairn'),
       ('PR', 'Puerto Rico', 'Puerto Rico'),
       ('PS', 'Palesztína', 'Palestine, State of'),
       ('PT', 'Portugália', 'Portugal'),
       ('PW', 'Palau', 'Palau'),
       ('PY', 'Paraguay', 'Paraguay'),
       ('QA', 'Katar', 'Qatar'),
       ('RE', 'Réunion', 'Reunion'),
       ('RO', 'Románia', 'Romania'),
       ('RS', 'Szerbia', 'Serbia'),
       ('RU', 'Oroszország', 'Russia Federation'),
       ('RW', 'Ruanda', 'Rwanda'),
       ('SA', 'Szaúd-Arábia', 'Saudi Arabia'),
       ('SB', 'Salamon-szigetek', 'Solomon Islands'),
       ('SC', 'Seychelle-szigetek', 'Seychelles'),
       ('SD', 'Szudán', 'Sudan'),
       ('SE', 'Svédország', 'Sweden'),
       ('SG', 'Szingapúr', 'Singapore'),
       ('SH', 'Szent Ilona, Ascension és Tristan da Cunha', 'Saint Helena, Ascension and Tristan da Cunha'),
       ('SI', 'Szlovénia', 'Slovenia'),
       ('SJ', 'Svalbard és Jan Mayen', 'Svalbard and Jan Mayen'),
       ('SK', 'Szlovákia', 'Slovakia'),
       ('SL', 'Sierra Leone', 'Sierra Leone'),
       ('SM', 'San Marino', 'San Marino'),
       ('SN', 'Szenegál', 'Senegal'),
       ('SO', 'Szomália', 'Somalia'),
       ('SR', 'Suriname', 'Suriname'),
       ('SS', 'Dél-Szudán', 'South Sudan'),
       ('ST', 'São Tomé és Príncipe', 'Sao Tome and Principe'),
       ('SV', 'Salvador', 'El Salvador'),
       ('SX', 'Sint Maarten', 'Sint Maarten'),
       ('SY', 'Szíria', 'Syrian Arab Republic'),
       ('SZ', 'Szváziföld', 'Eswatini'),
       ('TC', 'Turks- és Caicos-szigetek', 'Turks and Caicos Islands'),
       ('TD', 'Csád', 'Chad'),
       ('TF', 'Francia Déli és Antarktiszi Területek', 'French Southern Territories'),
       ('TG', 'Togo', 'Togo'),
       ('TH', 'Thaiföld', 'Thailand'),
       ('TJ', 'Tádzsikisztán', 'Tajikistan'),
       ('TK', 'Tokelau-szigetek', 'Tokelau'),
       ('TL', 'Kelet-Timor', 'Timor-Leste'),
       ('TM', 'Türkmenisztán', 'Turkmenistan'),
       ('TN', 'Tunézia', 'Tunisia'),
       ('TO', 'Tonga', 'Tonga'),
       ('TR', 'Törökország', 'Turkey'),
       ('TT', 'Trinidad és Tobago', 'Trinidad and Tobago'),
       ('TV', 'Tuvalu', 'Tuvalu'),
       ('TW', 'Tajvan', 'Taiwan, Province of China'),
       ('TZ', 'Tanzánia', 'Tanzania, United Republic of'),
       ('UA', 'Ukrajna', 'Ukraine'),
       ('UG', 'Uganda', 'Uganda'),
       ('UM', 'Az Amerikai Egyesült Államok Külső Szigetei', 'United States Minor Outlying Islands'),
       ('US', 'Egyesült Államok', 'United States of America'),
       ('UY', 'Uruguay', 'Uruguay'),
       ('UZ', 'Üzbegisztán', 'Uzbekistan'),
       ('VA', 'Apostoli Szentszék/Vatikán', 'Holy See (Vatican City State)'),
       ('VC', 'Saint Vincent és Grenadine-szigetek', 'Saint Vincent and the Grenadines'),
       ('VE', 'Venezuela', 'Venezuela'),
       ('VG', 'Brit Virgin-szigetek', 'Virgin Islands, British'),
       ('VI', 'Amerikai Virgin-szigetek', 'Virgin Islands, U.S.'),
       ('VN', 'Vietnám', 'Vietnam'),
       ('VU', 'Vanuatu', 'Vanuatu'),
       ('WF', 'Wallis és Futuna', 'Wallis and Futuna'),
       ('WS', 'Szamoa', 'Samoa'),
       ('XK', 'Koszovó', 'Kosovo'),
       ('YE', 'Jemen', 'Yemen'),
       ('YT', 'Mayotte', 'Mayotte'),
       ('ZA', 'Dél-Afrika', 'South Africa'),
       ('ZM', 'Zambia', 'Zambia'),
       ('ZW', 'Zimbabwe', 'Zimbabwe');